name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4

    - name: Install Miniconda
      run: |
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda
        echo "$HOME/miniconda/bin" >> $GITHUB_PATH

    - name: Initialize Conda
      run: |
        conda init bash
        source ~/.bashrc

    - name: Check environment file
      run: ls -l ./environment.yml

    - name: Install dependencies
      run: |
        conda env update --file ./environment.yml --name base

    - name: Install flake8
      run: |
        conda install -n base flake8 -y

    - name: Verify flake8 Installation
      run: |
        conda list -n base | grep flake8

    - name: Lint with flake8
      run: |
        conda run -n base flake8 .
        # Optional: Additional flake8 configurations
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        conda install pytest -y
        conda run -n base pytest
