name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4

    - name: Install Miniconda
      run: |
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda
        echo "$HOME/miniconda/bin" >> $GITHUB_PATH

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Check if environment.yml exists
      run: |
        ls -l ./environment.yml

    - name: Install dependencies
      run: |
        conda env update --file ./environment.yml --name base
        conda activate base
        # Ensure flake8 and pytest are installed in the environment
        conda install -n base flake8 pytest

    - name: Lint with flake8
      run: |
        # Lint the code using flake8 in the 'base' environment
        conda run -n base flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        conda run -n base flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        # Run tests using pytest
        conda run -n base pytest --maxfail=1 --disable-warnings -q
